#!/bin/bash
# blog is a limited bash leveled-logging utility.
#
# Usage:
#   blog [debug|info|warn|error] <message>
#
# Examples:
#   blog debug "Here is debug context."
#   blog info "Here is some useful info."
#   blog warn "Here is a warning. Hmm..."
#   blog error "Ack, an error! Oh no!"
#
# NOTE 2025-12-23: consider using https://github.com/charmbracelet/gum instead.

LB='\033[0;94m'
G='\033[0;32m'
Y='\033[1;33m'
R='\033[0;31m'
NC='\033[0m'

message=$2
case $1 in
  "debug") prefix="${LB}DEBUG:${NC}\t" ;;
  "info") prefix="${G}INFO:${NC}\t" ;;
  "warn") prefix="${Y}WARN:${NC}\t" ;;
  "error") prefix="${R}ERROR:${NC}\t" ;;
  *) blog error "Bad \`blog\` level: $1"; \
     bashdoc "$BASH_SOURCE"; \
     exit 1;;
esac

printf "${prefix}${message}\n"
