#!/bin/bash
# commits in the current repo pretty-represented in fzf, with patch previews.
# Uses fzf: https://github.com/junegunn/fzf

git log --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit \
| fzf -m --preview 'git show --color $(echo {} | awk "{print \$1}")'
