#!/bin/bash
# commits in the current repo pretty-represented in fzf, with patch previews.
# Uses fzf: https://github.com/junegunn/fzf

git log --pretty=format:'%h%d %s %cr <%an>' \
| fzf -m --preview 'git show --color $(echo {} | awk "{print \$1}")'
