#!/bin/bash
# Feedscan checks common feed suffixes for a webpage.
#
# Usage:
#   feedscan [url]
#
# Examples:
#   feedscan lukasschwab.me/blog
#   feedscan lukasschwab.me/blog/
#   feedscan http://lukasschwab.me/blog/
#   feedscan https://lukasschwab.me/blog/

base="$1"
if [ "${base: -1}" != "/" ]; then
  base="$base/"
fi

check () {
  local httpStatus=$(curl -Is --write-out %{http_code} --output /dev/null "$1");
  local class=$(($httpStatus / 100))
  case $class in
    2)
      blog info "$httpStatus: $1";;
    1|3|5)
      blog warn "$httpStatus: $1";;
    4)
      blog error "$httpStatus: $1";;
  esac
}

slugs=("atom" "rss" "feed")
for slug in "${slugs[@]}"; do
  check "${base}${slug}"
  check "${base}${slug}.xml"
done

# Check common non-XML cases for good measure.
check "${base}feed.atom"
check "${base}feed.json"
check "${base}?format=rss"
