#!/bin/bash
# Find the path to a package buried in your GOPATH.
# Uses fzf: https://github.com/junegunn/fzf
#
# To conveniently cd to the found directory, set a function in your .zshrc:
#   goto() { cd $(gofind) }
cd $GOPATH/src;
find * -type d -not -path '*/\.*' |
if [ $# -eq 0 ]; then	# Query for first argument if provided.
	fzf
else
	fzf -q $1
fi | pbcopy