#!/bin/bash
# Find the path to a package buried in your GOPATH.
# Uses fzf: https://github.com/junegunn/fzf
#
# To conveniently cd to the found directory, set a function in your .zshrc:
#   goto() { cd $(gofind) }
cd $GOPATH/src;
{ echo $GOPATH/src; find * -type d -not -path '*/\.*' | fzf; } | tr "\n" "/";
echo "";
