#!/bin/bash
# GO RElease: routine checks for go packages.

G='\033[1;32m'
B='\033[0;36m'
NC='\033[0m'
echo -e "${B}» go fmt${NC}" &&
go fmt ./... &&
echo -e "${B}» go vet${NC}" &&
go vet ./... &&
echo -e "${B}» golint${NC}" &&
golint ./... &&
echo -e "${B}» go test${NC}" &&
go test;
