#!/bin/bash
# Routine checks for go packages before releasing them.
# echo colors how-to: https://stackoverflow.com/questions/5947742/
G='\033[1;32m'
NC='\033[0m'
echo -e "${G}» go fmt${NC}";
go fmt;
echo -e "${G}» go vet${NC}";
go vet;
echo -e "${G}» golint${NC}";
golint;
echo -e "${G}» go test${NC}";
go test;
