#!/bin/bash
# hf pipes history into fzf for finding commands you can't remember.

croppedhistory |
awk '!a[$0]++' |	# Deduplicate lines.
if [ $# -eq 0 ]; then	# Query for first argument if provided.
	fzf
else
	fzf -q $1
fi | pbcopy

