#!/usr/bin/env bash
# line 10 prints line 10 from stdin. For example, cat some_big_file | line 10
# prints line 10 of a file.
#
# Adapted from:
# - https://evanhahn.com/scripts-i-wrote-that-i-use-all-the-time/
# - https://codeberg.org/EvanHahn/dotfiles/src/commit/843b9ee13d949d346a4a73ccee2a99351aed285b/home/bin/bin/line

sed -n "${1}p"
