#!/bin/bash
# lsf pipes ls results into fzf for finding commands you can't remember.
#
# Standard useage:
# 	lsf
# List all files:
# 	lsf -a

# If a first argument is provided, use ls -a.
if [ $# -eq 0 ]; then
	ls
else
	ls -a
fi |
fzf -m |
tr '\n' ' ' | # Move to single line
pbcopy
