#!/usr/bin/env ruby
# nato bar returns Bravo Alfa Romeo. I use this most often when talking to
# customer service and need to read out a long alphanumeric string, which has
# only happened a couple of times in my whole life. But it’s sometimes useful!
#
# Blog post source: https://evanhahn.com/scripts-i-wrote-that-i-use-all-the-time/
# Source: https://codeberg.org/EvanHahn/dotfiles/src/commit/843b9ee13d949d346a4a73ccee2a99351aed285b/home/bin/bin/nato

DICTIONARY = {
  "a" => "Alfa",
  "b" => "Bravo",
  "c" => "Charlie",
  "d" => "Delta",
  "e" => "Echo",
  "f" => "Foxtrot",
  "g" => "Golf",
  "h" => "Hotel",
  "i" => "India",
  "j" => "Juliett",
  "k" => "Kilo",
  "l" => "Lima",
  "m" => "Mike",
  "n" => "November",
  "o" => "Oscar",
  "p" => "Papa",
  "q" => "Quebec",
  "r" => "Romeo",
  "s" => "Sierra",
  "t" => "Tango",
  "u" => "Uniform",
  "v" => "Victor",
  "w" => "Whiskey",
  "x" => "X-ray",
  "y" => "Yankee",
  "z" => "Zulu",
  "1" => "One",
  "2" => "Two",
  "3" => "Three",
  "4" => "Four",
  "5" => "Five",
  "6" => "Six",
  "7" => "Seven",
  "8" => "Eight",
  "9" => "Nine",
  "0" => "Zero"
}

ARGV.join(' ').split(' ').each do |word|
  letters = word.downcase.each_char.map do |char|
    DICTIONARY.fetch char, char
  end

  puts letters.join(' ')
end
