#!/usr/bin/env bash
# ARG WRANGLING
if [[ $# -eq 0 ]] ; then
    echo 'Usage: `topdf somefile.md`'
    exit 0
fi
INFILE=$1
NAME=${1%.md}
PDFNAME=${NAME}.pdf
# PROCESSING
sed -e 's/––/---/g' ${INFILE} | # Better em-dashes
sed -e 's/<br>/\\\newline /g' | # Support <br> for line breaks. Add any other operations after this...
pandoc --from=markdown --pdf-engine=xelatex -o ${PDFNAME} --variable urlcolor=NavyBlue "${@:2:99}" # ...and before this.
# CONVENIENCE
echo "Done: created" $PDFNAME
